name: Feature request
description: Propose a feature for OrchWiz Agent VPC workflows.
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: Describe the workflow pain point.
    validations:
      required: true

  - type: dropdown
    id: pillar
    attributes:
      label: Agent VPC pillar
      description: Which pillar does this feature improve most?
      options:
        - Boundary
        - Control
        - Traceability
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should OrchWiz do?
      placeholder: Describe API/UI/runtime behavior.
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Provide testable criteria for done.
      placeholder: |
        - [ ] criterion 1
        - [ ] criterion 2
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links, references, logs, or screenshots.
      placeholder: Optional supporting details.
