export const SHIPYARD_BILLING_CURRENCY = "eur" as const
export const SHIPYARD_BILLING_MIN_TOPUP_CENTS = 500
export const SHIPYARD_BILLING_QUOTE_HOURS = 720
export const SHIPYARD_BILLING_CONVENIENCE_FEE_PERCENT = 0.1
export const SHIPYARD_BILLING_CONVENIENCE_FEE_PERCENT_DISPLAY = 10

export type ShipyardBillingCurrencyCode = typeof SHIPYARD_BILLING_CURRENCY
