import test from "node:test"
import assert from "node:assert/strict"
import {
  BRIDGE_CREW_ROLE_ORDER,
} from "./bridge-crew"
import {
  SHIP_DEPLOYMENT_OVERVIEW_VERSION,
  buildShipDeploymentOverview,
  hasCompleteBridgeCrewCoverage,
  readShipDeploymentOverview,
} from "./deployment-overview"

const LOCAL_INFRA = {
  kind: "kind",
  kubeContext: "kind-orchwiz",
  namespace: "orchwiz-starship",
  terraformWorkspace: "starship-local",
  terraformEnvDir: "infra/terraform/environments/starship-local",
  ansibleInventory: "infra/ansible/inventory/local.ini",
  ansiblePlaybook: "infra/ansible/playbooks/starship_local.yml",
} as const

test("buildShipDeploymentOverview builds full topology coverage", () => {
  const overview = buildShipDeploymentOverview({
    deploymentProfile: "local_starship_build",
    provisioningMode: "terraform_ansible",
    nodeType: "local",
    infrastructure: LOCAL_INFRA,
    crewRoles: BRIDGE_CREW_ROLE_ORDER,
    generatedAt: new Date("2026-02-10T12:00:00.000Z"),
  })

  assert.equal(overview.version, SHIP_DEPLOYMENT_OVERVIEW_VERSION)
  assert.equal(overview.coverage, "full_topology")
  assert.equal(overview.topology.components.length, 19)
  assert.deepEqual(overview.topology.groups, ["users", "bridge", "openclaw", "obs", "k8s"])
})

test("overview enforces six bridge pods when all roles are selected", () => {
  const overview = buildShipDeploymentOverview({
    deploymentProfile: "local_starship_build",
    provisioningMode: "terraform_ansible",
    nodeType: "local",
    infrastructure: LOCAL_INFRA,
    crewRoles: BRIDGE_CREW_ROLE_ORDER,
  })

  assert.equal(overview.crewPolicy.compliant, true)
  assert.equal(overview.workloads.bridgeAgentPods, 6)
})

test("overview includes full USS-K8s observability stack", () => {
  const overview = buildShipDeploymentOverview({
    deploymentProfile: "cloud_shipyard",
    provisioningMode: "terraform_ansible",
    nodeType: "cloud",
    infrastructure: {
      ...LOCAL_INFRA,
      kind: "existing_k8s",
      kubeContext: "cloud-prod",
      namespace: "orchwiz-shipyard",
    },
    crewRoles: BRIDGE_CREW_ROLE_ORDER,
  })

  const obsComponents = overview.topology.components.filter((component) => component.group === "obs")
  assert.deepEqual(
    obsComponents.map((component) => component.id),
    ["lf", "ch", "loki", "prom", "graf", "evt"],
  )
  assert.equal(overview.workloads.observabilityPods, 6)
})

test("overview requirements include auto-generated local secrets and external warnings", () => {
  const overview = buildShipDeploymentOverview({
    deploymentProfile: "local_starship_build",
    provisioningMode: "terraform_ansible",
    nodeType: "local",
    infrastructure: LOCAL_INFRA,
    crewRoles: BRIDGE_CREW_ROLE_ORDER,
  })

  const autoGenerated = overview.requirements.filter((requirement) => requirement.status === "auto_generated")
  assert.ok(autoGenerated.length >= 3)
  assert.ok(autoGenerated.every((requirement) => typeof requirement.secretRef === "string" && requirement.secretRef.length > 0))

  const externalWarnings = overview.requirements.filter(
    (requirement) => requirement.status === "warning" && requirement.scope === "external",
  )
  assert.ok(externalWarnings.length >= 1)
})

test("overview computes stable resource totals", () => {
  const overview = buildShipDeploymentOverview({
    deploymentProfile: "local_starship_build",
    provisioningMode: "terraform_ansible",
    nodeType: "local",
    infrastructure: LOCAL_INFRA,
    crewRoles: BRIDGE_CREW_ROLE_ORDER,
  })

  assert.deepEqual(overview.resources.runtime, { cpuMillicores: 350, memoryMiB: 480 })
  assert.deepEqual(overview.resources.observability, { cpuMillicores: 900, memoryMiB: 1568 })
  assert.deepEqual(overview.resources.totals, { cpuMillicores: 2700, memoryMiB: 3968 })
})

test("readShipDeploymentOverview parses valid metadata and rejects malformed payloads", () => {
  const overview = buildShipDeploymentOverview({
    deploymentProfile: "local_starship_build",
    provisioningMode: "terraform_ansible",
    nodeType: "local",
    infrastructure: LOCAL_INFRA,
    crewRoles: BRIDGE_CREW_ROLE_ORDER,
  })

  const parsed = readShipDeploymentOverview({ deploymentOverview: overview })
  assert.ok(parsed)
  assert.equal(parsed?.version, SHIP_DEPLOYMENT_OVERVIEW_VERSION)

  assert.equal(readShipDeploymentOverview(null), null)
  assert.equal(readShipDeploymentOverview({}), null)
  assert.equal(
    readShipDeploymentOverview({
      deploymentOverview: {
        ...overview,
        version: "shipyard_overview_v2",
      },
    }),
    null,
  )
  assert.equal(
    readShipDeploymentOverview({
      deploymentOverview: {
        ...overview,
        resources: {
          ...overview.resources,
          totals: {
            cpuMillicores: "2700",
            memoryMiB: 3968,
          },
        },
      },
    }),
    null,
  )
})

test("hasCompleteBridgeCrewCoverage enforces exact six-role coverage", () => {
  assert.equal(hasCompleteBridgeCrewCoverage(BRIDGE_CREW_ROLE_ORDER), true)
  assert.equal(hasCompleteBridgeCrewCoverage(["xo", "ops", "eng"]), false)
  assert.equal(hasCompleteBridgeCrewCoverage(["xo", "ops", "eng", "sec", "med", "cou", "xo"]), true)
  assert.equal(hasCompleteBridgeCrewCoverage(["xo", "ops", "eng", "sec", "med", "invalid"]), false)
})
