import type {
  DeploymentOverviewRequirement,
  DeploymentOverviewRequirementCategory,
  ShipDeploymentOverview,
} from "@/lib/shipyard/deployment-overview"
import type { ShipBaseRequirementsEstimate } from "@/lib/shipyard/resource-estimation"

interface ResourceSlice {
  cpuMillicores: number
  memoryMiB: number
}

export type LaunchReadiness = "ready" | "ready_with_warnings"

export interface LaunchReviewWarning {
  id: string
  title: string
  description: string
  category: DeploymentOverviewRequirementCategory
  hint: string | null
}

export interface LaunchReviewSummary {
  readiness: LaunchReadiness
  requirementCounts: {
    ready: number
    warning: number
    autoGenerated: number
  }
  prioritizedWarnings: LaunchReviewWarning[]
  workloads: {
    plannedWorkloads: number
    plannedPods: number
    bridgeAgentPods: number
    runtimePods: number
    observabilityPods: number
    coreAppPods: number
  }
  provisioningRealityCounts: {
    currentlyProvisioned: number
    plannedOnly: number
  }
  resources: {
    totalPlanned: ResourceSlice
    baseline: ResourceSlice
    crewAddOn: ResourceSlice
    runtimeAndObservability: ResourceSlice
  }
}

const WARNING_CATEGORY_PRIORITY: Record<DeploymentOverviewRequirementCategory, number> = {
  infrastructure: 0,
  storage: 1,
  network: 2,
  integrations: 3,
  credential: 4,
}

function addResourceSlices(left: ResourceSlice, right: ResourceSlice): ResourceSlice {
  return {
    cpuMillicores: left.cpuMillicores + right.cpuMillicores,
    memoryMiB: left.memoryMiB + right.memoryMiB,
  }
}

function sortWarnings(left: DeploymentOverviewRequirement, right: DeploymentOverviewRequirement): number {
  const leftPriority = WARNING_CATEGORY_PRIORITY[left.category]
  const rightPriority = WARNING_CATEGORY_PRIORITY[right.category]
  if (leftPriority !== rightPriority) {
    return leftPriority - rightPriority
  }

  const leftTitle = left.title.toLowerCase()
  const rightTitle = right.title.toLowerCase()
  if (leftTitle !== rightTitle) {
    return leftTitle.localeCompare(rightTitle)
  }

  return left.id.localeCompare(right.id)
}

export function buildReviewLaunchSummary(
  overview: ShipDeploymentOverview,
  baseEstimate: ShipBaseRequirementsEstimate,
): LaunchReviewSummary {
  let readyCount = 0
  let warningCount = 0
  let autoGeneratedCount = 0

  for (const requirement of overview.requirements) {
    if (requirement.status === "ready") {
      readyCount += 1
      continue
    }
    if (requirement.status === "warning") {
      warningCount += 1
      continue
    }
    autoGeneratedCount += 1
  }

  const prioritizedWarnings = overview.requirements
    .filter((requirement) => requirement.status === "warning")
    .slice()
    .sort(sortWarnings)
    .map((requirement) => ({
      id: requirement.id,
      title: requirement.title,
      description: requirement.description,
      category: requirement.category,
      hint: requirement.hints[0] || null,
    }))

  let currentlyProvisionedCount = 0
  let plannedOnlyCount = 0
  for (const component of overview.topology.components) {
    if (component.provisioningReality === "currently_provisioned") {
      currentlyProvisionedCount += 1
    } else {
      plannedOnlyCount += 1
    }
  }

  return {
    readiness: warningCount > 0 ? "ready_with_warnings" : "ready",
    requirementCounts: {
      ready: readyCount,
      warning: warningCount,
      autoGenerated: autoGeneratedCount,
    },
    prioritizedWarnings,
    workloads: {
      plannedWorkloads: overview.workloads.plannedWorkloads,
      plannedPods: overview.workloads.plannedPods,
      bridgeAgentPods: overview.workloads.bridgeAgentPods,
      runtimePods: overview.workloads.runtimePods,
      observabilityPods: overview.workloads.observabilityPods,
      coreAppPods: overview.workloads.coreAppPods,
    },
    provisioningRealityCounts: {
      currentlyProvisioned: currentlyProvisionedCount,
      plannedOnly: plannedOnlyCount,
    },
    resources: {
      totalPlanned: { ...overview.resources.totals },
      baseline: { ...baseEstimate.baseline },
      crewAddOn: { ...baseEstimate.crew.totals },
      runtimeAndObservability: addResourceSlices(
        overview.resources.runtime,
        overview.resources.observability,
      ),
    },
  }
}
