import test from "node:test"
import assert from "node:assert/strict"
import {
  SHIP_DEPLOYMENT_OVERVIEW_VERSION,
  type ShipDeploymentOverview,
} from "@/lib/shipyard/deployment-overview"
import {
  SHIP_BASE_REQUIREMENTS_ESTIMATE_VERSION,
  type ShipBaseRequirementsEstimate,
} from "@/lib/shipyard/resource-estimation"
import { buildReviewLaunchSummary } from "./review-launch-summary"

function createOverview(overrides?: Partial<ShipDeploymentOverview>): ShipDeploymentOverview {
  return {
    version: SHIP_DEPLOYMENT_OVERVIEW_VERSION,
    generatedAt: "2026-02-10T10:00:00.000Z",
    coverage: "full_topology",
    topology: {
      groups: ["users", "bridge", "openclaw", "obs", "k8s"],
      components: [
        {
          id: "app",
          label: "Workloads",
          sublabel: "",
          group: "k8s",
          groupLabel: "Kubernetes Cluster",
          componentType: "k8s-workload",
          workloadKind: "deployment",
          provisioningReality: "currently_provisioned",
          enabled: true,
          replicaCount: 1,
          resources: { cpuMillicores: 0, memoryMiB: 0 },
        },
        {
          id: "gw",
          label: "OpenClaw Gateway",
          sublabel: "",
          group: "openclaw",
          groupLabel: "OpenClaw Runtime",
          componentType: "runtime",
          workloadKind: "deployment",
          provisioningReality: "planned_only",
          enabled: true,
          replicaCount: 1,
          resources: { cpuMillicores: 200, memoryMiB: 256 },
        },
      ],
      provisioningRealityNote: "Reality note",
    },
    crewPolicy: {
      requiredRoles: ["xo", "ops", "eng", "sec", "med", "cou"],
      selectedRoles: ["xo", "ops", "eng", "sec", "med", "cou"],
      compliant: true,
    },
    infrastructureTarget: {
      deploymentProfile: "local_starship_build",
      provisioningMode: "terraform_ansible",
      nodeType: "local",
      kind: "kind",
      kubeContext: "kind-orchwiz",
      namespace: "orchwiz-starship",
      terraformWorkspace: "starship-local",
      terraformEnvDir: "infra/terraform/environments/starship-local",
      ansibleInventory: "infra/ansible/inventory/local.ini",
      ansiblePlaybook: "infra/ansible/playbooks/starship_local.yml",
    },
    workloads: {
      plannedWorkloads: 10,
      plannedPods: 12,
      bridgeAgentPods: 6,
      runtimePods: 3,
      observabilityPods: 2,
      coreAppPods: 1,
    },
    resources: {
      baseline: { cpuMillicores: 750, memoryMiB: 1024 },
      crew: { cpuMillicores: 700, memoryMiB: 896 },
      runtime: { cpuMillicores: 350, memoryMiB: 480 },
      observability: { cpuMillicores: 900, memoryMiB: 1568 },
      totals: { cpuMillicores: 2700, memoryMiB: 3968 },
    },
    requirements: [
      {
        id: "infra.kubeContext",
        title: "Kubernetes context",
        description: "Target kube context is set for this launch profile.",
        category: "infrastructure",
        status: "ready",
        scope: "cluster",
        source: "user",
        value: "kind-orchwiz",
        hints: ["Verify context access."],
      },
      {
        id: "storage.clickhouse",
        title: "ClickHouse persistent volume",
        description: "ClickHouse requires durable storage class allocation.",
        category: "storage",
        status: "warning",
        scope: "cluster",
        source: "derived",
        hints: ["Confirm StorageClass availability."],
      },
      {
        id: "credential.auth",
        title: "BETTER_AUTH_SECRET",
        description: "Generated local secret reference for auth signing.",
        category: "credential",
        status: "auto_generated",
        scope: "local",
        source: "auto",
        secretRef: "orchwiz-starship/orchwiz-generated-auth-secret",
        hints: ["Rotate for production."],
      },
    ],
    ...overrides,
  }
}

function createBaseEstimate(overrides?: Partial<ShipBaseRequirementsEstimate>): ShipBaseRequirementsEstimate {
  return {
    version: SHIP_BASE_REQUIREMENTS_ESTIMATE_VERSION,
    profile: "local_starship_build",
    baseline: { cpuMillicores: 750, memoryMiB: 1024 },
    crew: {
      roles: [
        { role: "xo", cpuMillicores: 100, memoryMiB: 128 },
        { role: "ops", cpuMillicores: 150, memoryMiB: 192 },
      ],
      totals: { cpuMillicores: 250, memoryMiB: 320 },
    },
    totals: { cpuMillicores: 1000, memoryMiB: 1344 },
    ...overrides,
  }
}

test("computes requirement status counts and readiness", () => {
  const summary = buildReviewLaunchSummary(createOverview(), createBaseEstimate())

  assert.equal(summary.readiness, "ready_with_warnings")
  assert.deepEqual(summary.requirementCounts, {
    ready: 1,
    warning: 1,
    autoGenerated: 1,
  })
})

test("prioritizes warnings by deterministic category ordering", () => {
  const overview = createOverview({
    requirements: [
      {
        id: "credential.key",
        title: "Credential warning",
        description: "Credential issue",
        category: "credential",
        status: "warning",
        scope: "cluster",
        source: "derived",
        hints: ["Credential hint"],
      },
      {
        id: "network.exposure",
        title: "Network warning",
        description: "Network issue",
        category: "network",
        status: "warning",
        scope: "cluster",
        source: "derived",
        hints: ["Network hint"],
      },
      {
        id: "infra.context",
        title: "Infrastructure warning",
        description: "Infra issue",
        category: "infrastructure",
        status: "warning",
        scope: "cluster",
        source: "derived",
        hints: ["Infra hint"],
      },
      {
        id: "integrations.provider",
        title: "Integrations warning",
        description: "Integrations issue",
        category: "integrations",
        status: "warning",
        scope: "external",
        source: "derived",
        hints: ["Integrations hint"],
      },
      {
        id: "storage.pvc",
        title: "Storage warning",
        description: "Storage issue",
        category: "storage",
        status: "warning",
        scope: "cluster",
        source: "derived",
        hints: ["Storage hint"],
      },
    ],
  })

  const summary = buildReviewLaunchSummary(overview, createBaseEstimate())
  assert.deepEqual(
    summary.prioritizedWarnings.map((warning) => warning.category),
    ["infrastructure", "storage", "network", "integrations", "credential"],
  )
})

test("computes provisioning reality counts from topology components", () => {
  const overview = createOverview({
    topology: {
      groups: ["k8s"],
      provisioningRealityNote: "Reality note",
      components: [
        {
          id: "app",
          label: "App",
          sublabel: "",
          group: "k8s",
          groupLabel: "Kubernetes Cluster",
          componentType: "k8s-workload",
          workloadKind: "deployment",
          provisioningReality: "currently_provisioned",
          enabled: true,
          replicaCount: 1,
          resources: { cpuMillicores: 0, memoryMiB: 0 },
        },
        {
          id: "gw",
          label: "Gateway",
          sublabel: "",
          group: "openclaw",
          groupLabel: "OpenClaw Runtime",
          componentType: "runtime",
          workloadKind: "deployment",
          provisioningReality: "planned_only",
          enabled: true,
          replicaCount: 1,
          resources: { cpuMillicores: 200, memoryMiB: 256 },
        },
        {
          id: "loki",
          label: "Loki",
          sublabel: "",
          group: "obs",
          groupLabel: "Observability",
          componentType: "observability",
          workloadKind: "statefulset",
          provisioningReality: "planned_only",
          enabled: true,
          replicaCount: 1,
          resources: { cpuMillicores: 150, memoryMiB: 256 },
        },
      ],
    },
  })

  const summary = buildReviewLaunchSummary(overview, createBaseEstimate())
  assert.deepEqual(summary.provisioningRealityCounts, {
    currentlyProvisioned: 1,
    plannedOnly: 2,
  })
})

test("computes resource slices including runtime plus observability", () => {
  const summary = buildReviewLaunchSummary(createOverview(), createBaseEstimate())

  assert.deepEqual(summary.resources.totalPlanned, { cpuMillicores: 2700, memoryMiB: 3968 })
  assert.deepEqual(summary.resources.baseline, { cpuMillicores: 750, memoryMiB: 1024 })
  assert.deepEqual(summary.resources.crewAddOn, { cpuMillicores: 250, memoryMiB: 320 })
  assert.deepEqual(summary.resources.runtimeAndObservability, {
    cpuMillicores: 1250,
    memoryMiB: 2048,
  })
})
