/* eslint-disable */
// This file is auto-generated by node/scripts/generate-open-source-attributions.ts.
// Do not edit by hand.

export type DependencyKind = "dependency" | "devDependency"

export interface WorkspaceOccurrence {
  workspaceId: string
  workspaceLabel: string
  kind: DependencyKind
  requested: string
  version: string | null
}

export interface OpenSourceAttribution {
  name: string
  description: string | null
  license: string | null
  url: string
  occurrences: WorkspaceOccurrence[]
}

export const OPEN_SOURCE_ATTRIBUTIONS: OpenSourceAttribution[] = [
  {
    "name": "@better-auth/passkey",
    "description": "Passkey plugin for Better Auth",
    "license": "MIT",
    "url": "https://www.better-auth.com/docs/plugins/passkey",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "dependency",
        "requested": "^1.4.15",
        "version": "1.4.18"
      }
    ]
  },
  {
    "name": "@langfuse/client",
    "description": "Langfuse API client for universal JavaScript environments",
    "license": "MIT",
    "url": "https://github.com/langfuse/langfuse-js",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "dependency",
        "requested": "^4.6.0",
        "version": "4.6.0"
      }
    ]
  },
  {
    "name": "@meshsdk/core",
    "description": "Mesh SDK Core - https://meshjs.dev/",
    "license": "Apache-2.0",
    "url": "https://www.npmjs.com/package/@meshsdk/core",
    "occurrences": [
      {
        "workspaceId": "wallet-enclave",
        "workspaceLabel": "Wallet Enclave",
        "kind": "dependency",
        "requested": "^1.8.11",
        "version": "1.8.14"
      },
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "dependency",
        "requested": "^1.8.11",
        "version": "1.8.14"
      }
    ]
  },
  {
    "name": "@octokit/rest",
    "description": "GitHub REST API client for Node.js",
    "license": "MIT",
    "url": "https://www.npmjs.com/package/@octokit/rest",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "dependency",
        "requested": "^22.0.1",
        "version": "22.0.1"
      }
    ]
  },
  {
    "name": "@prisma/adapter-pg",
    "description": "Prisma's driver adapter for \"pg\"",
    "license": "Apache-2.0",
    "url": "https://github.com/prisma/prisma",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "dependency",
        "requested": "^7.3.0",
        "version": "7.3.0"
      }
    ]
  },
  {
    "name": "@prisma/client",
    "description": "Prisma Client is an auto-generated, type-safe and modern JavaScript/TypeScript ORM for Node.js that's tailored to your data. Supports PostgreSQL, CockroachDB, MySQL, MariaDB, SQL Server, SQLite & MongoDB databases.",
    "license": "Apache-2.0",
    "url": "https://www.prisma.io",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "dependency",
        "requested": "^7.3.0",
        "version": "7.3.0"
      }
    ]
  },
  {
    "name": "@tailwindcss/postcss",
    "description": "PostCSS plugin for Tailwind CSS, a utility-first CSS framework for rapidly building custom user interfaces",
    "license": "MIT",
    "url": "https://tailwindcss.com",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "devDependency",
        "requested": "^4.1.18",
        "version": "4.1.18"
      }
    ]
  },
  {
    "name": "@types/express",
    "description": "TypeScript definitions for express",
    "license": "MIT",
    "url": "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/express",
    "occurrences": [
      {
        "workspaceId": "data-core",
        "workspaceLabel": "Data Core",
        "kind": "devDependency",
        "requested": "^4.17.23",
        "version": "4.17.25"
      },
      {
        "workspaceId": "provider-proxy",
        "workspaceLabel": "Provider Proxy",
        "kind": "devDependency",
        "requested": "^4.17.23",
        "version": "4.17.25"
      },
      {
        "workspaceId": "wallet-enclave",
        "workspaceLabel": "Wallet Enclave",
        "kind": "devDependency",
        "requested": "^4.17.23",
        "version": "4.17.25"
      }
    ]
  },
  {
    "name": "@types/node",
    "description": "TypeScript definitions for node",
    "license": "MIT",
    "url": "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node",
    "occurrences": [
      {
        "workspaceId": "data-core",
        "workspaceLabel": "Data Core",
        "kind": "devDependency",
        "requested": "^22.10.2",
        "version": "22.19.11"
      },
      {
        "workspaceId": "desktop",
        "workspaceLabel": "Desktop App",
        "kind": "devDependency",
        "requested": "^25.0.10",
        "version": "25.2.3"
      },
      {
        "workspaceId": "provider-proxy",
        "workspaceLabel": "Provider Proxy",
        "kind": "devDependency",
        "requested": "^22.10.2",
        "version": "22.19.11"
      },
      {
        "workspaceId": "wallet-enclave",
        "workspaceLabel": "Wallet Enclave",
        "kind": "devDependency",
        "requested": "^22.10.2",
        "version": "22.19.10"
      },
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "devDependency",
        "requested": "^25.0.10",
        "version": "25.0.10"
      }
    ]
  },
  {
    "name": "@types/pg",
    "description": "TypeScript definitions for pg",
    "license": "MIT",
    "url": "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/pg",
    "occurrences": [
      {
        "workspaceId": "data-core",
        "workspaceLabel": "Data Core",
        "kind": "devDependency",
        "requested": "^8.15.6",
        "version": "8.16.0"
      }
    ]
  },
  {
    "name": "@types/react",
    "description": "TypeScript definitions for react",
    "license": "MIT",
    "url": "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "devDependency",
        "requested": "^19.2.9",
        "version": "19.2.9"
      }
    ]
  },
  {
    "name": "@types/react-dom",
    "description": "TypeScript definitions for react-dom",
    "license": "MIT",
    "url": "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-dom",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "devDependency",
        "requested": "^19.2.3",
        "version": "19.2.3"
      }
    ]
  },
  {
    "name": "@types/three",
    "description": "TypeScript definitions for three",
    "license": "MIT",
    "url": "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/three",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "devDependency",
        "requested": "^0.182.0",
        "version": "0.182.0"
      }
    ]
  },
  {
    "name": "@types/ws",
    "description": "TypeScript definitions for ws",
    "license": "MIT",
    "url": "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ws",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "devDependency",
        "requested": "^8.18.1",
        "version": "8.18.1"
      }
    ]
  },
  {
    "name": "autoprefixer",
    "description": "Parse CSS and add vendor prefixes to CSS rules using values from the Can I Use website",
    "license": "MIT",
    "url": "https://www.npmjs.com/package/autoprefixer",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "devDependency",
        "requested": "^10.4.19",
        "version": "10.4.23"
      }
    ]
  },
  {
    "name": "better-auth",
    "description": "The most comprehensive authentication framework for TypeScript.",
    "license": "MIT",
    "url": "https://better-auth.com",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "dependency",
        "requested": "^1.0.0",
        "version": "1.4.18"
      }
    ]
  },
  {
    "name": "cbor-x",
    "description": "Ultra-fast and conformant CBOR (RFC 8949) implementation with support for numerous tag extensions including records and structured cloning",
    "license": "MIT",
    "url": "http://github.com/kriszyp/cbor-x",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "dependency",
        "requested": "^1.6.0",
        "version": "1.6.0"
      }
    ]
  },
  {
    "name": "dotenv",
    "description": "Loads environment variables from .env file",
    "license": "BSD-2-Clause",
    "url": "https://github.com/motdotla/dotenv#readme",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "dependency",
        "requested": "^17.2.3",
        "version": "17.2.3"
      }
    ]
  },
  {
    "name": "electron",
    "description": "Build cross platform desktop apps with JavaScript, HTML, and CSS",
    "license": "MIT",
    "url": "https://github.com/electron/electron",
    "occurrences": [
      {
        "workspaceId": "desktop",
        "workspaceLabel": "Desktop App",
        "kind": "devDependency",
        "requested": "^32.0.0",
        "version": "32.3.3"
      }
    ]
  },
  {
    "name": "electron-builder",
    "description": "A complete solution to package and build a ready for distribution Electron app for MacOS, Windows and Linux with “auto update” support out of the box",
    "license": "MIT",
    "url": "https://github.com/electron-userland/electron-builder",
    "occurrences": [
      {
        "workspaceId": "desktop",
        "workspaceLabel": "Desktop App",
        "kind": "devDependency",
        "requested": "^24.13.3",
        "version": "24.13.3"
      }
    ]
  },
  {
    "name": "eslint",
    "description": "An AST-based pattern checker for JavaScript.",
    "license": "MIT",
    "url": "https://eslint.org",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "devDependency",
        "requested": "^9.39.2",
        "version": "9.39.2"
      }
    ]
  },
  {
    "name": "eslint-config-next",
    "description": "ESLint configuration used by Next.js.",
    "license": "MIT",
    "url": "https://nextjs.org/docs/app/api-reference/config/eslint",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "devDependency",
        "requested": "^16.1.4",
        "version": "16.1.4"
      }
    ]
  },
  {
    "name": "express",
    "description": "Fast, unopinionated, minimalist web framework",
    "license": "MIT",
    "url": "http://expressjs.com/",
    "occurrences": [
      {
        "workspaceId": "data-core",
        "workspaceLabel": "Data Core",
        "kind": "dependency",
        "requested": "^4.21.2",
        "version": "4.22.1"
      },
      {
        "workspaceId": "provider-proxy",
        "workspaceLabel": "Provider Proxy",
        "kind": "dependency",
        "requested": "^4.21.2",
        "version": "4.22.1"
      },
      {
        "workspaceId": "wallet-enclave",
        "workspaceLabel": "Wallet Enclave",
        "kind": "dependency",
        "requested": "^4.21.2",
        "version": "4.22.1"
      }
    ]
  },
  {
    "name": "lucide-react",
    "description": "A Lucide icon library package for React applications.",
    "license": "ISC",
    "url": "https://lucide.dev",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "dependency",
        "requested": "^0.563.0",
        "version": "0.563.0"
      }
    ]
  },
  {
    "name": "next",
    "description": "The React Framework",
    "license": "MIT",
    "url": "https://nextjs.org",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "dependency",
        "requested": "^16.1.4",
        "version": "16.1.6"
      }
    ]
  },
  {
    "name": "pg",
    "description": "PostgreSQL client - pure javascript & libpq with the same API",
    "license": "MIT",
    "url": "https://github.com/brianc/node-postgres",
    "occurrences": [
      {
        "workspaceId": "data-core",
        "workspaceLabel": "Data Core",
        "kind": "dependency",
        "requested": "^8.17.2",
        "version": "8.18.0"
      },
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "dependency",
        "requested": "^8.17.2",
        "version": "8.17.2"
      }
    ]
  },
  {
    "name": "playwright",
    "description": "A high-level API to automate web browsers",
    "license": "Apache-2.0",
    "url": "https://playwright.dev",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "devDependency",
        "requested": "^1.58.2",
        "version": "1.58.2"
      }
    ]
  },
  {
    "name": "postcss",
    "description": "Tool for transforming styles with JS plugins",
    "license": "MIT",
    "url": "https://postcss.org/",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "devDependency",
        "requested": "^8.4.38",
        "version": "8.5.6"
      }
    ]
  },
  {
    "name": "prisma",
    "description": "Prisma is an open-source database toolkit. It includes a JavaScript/TypeScript ORM for Node.js, migrations and a modern GUI to view and edit the data in your database. You can use Prisma in new projects or add it to an existing one.",
    "license": "Apache-2.0",
    "url": "https://www.prisma.io",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "devDependency",
        "requested": "^7.3.0",
        "version": "7.3.0"
      }
    ]
  },
  {
    "name": "react",
    "description": "React is a JavaScript library for building user interfaces.",
    "license": "MIT",
    "url": "https://react.dev/",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "dependency",
        "requested": "^19.2.3",
        "version": "19.2.3"
      }
    ]
  },
  {
    "name": "react-dom",
    "description": "React package for working with the DOM.",
    "license": "MIT",
    "url": "https://react.dev/",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "dependency",
        "requested": "^19.2.3",
        "version": "19.2.3"
      }
    ]
  },
  {
    "name": "react-markdown",
    "description": "React component to render markdown",
    "license": "MIT",
    "url": "https://www.npmjs.com/package/react-markdown",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "dependency",
        "requested": "^10.1.0",
        "version": "10.1.0"
      }
    ]
  },
  {
    "name": "reactflow",
    "description": "A highly customizable React library for building node-based editors and interactive flow charts",
    "license": "MIT",
    "url": "https://github.com/xyflow/xyflow",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "dependency",
        "requested": "^11.11.4",
        "version": "11.11.4"
      }
    ]
  },
  {
    "name": "remark-gfm",
    "description": "remark plugin to support GFM (autolink literals, footnotes, strikethrough, tables, tasklists)",
    "license": "MIT",
    "url": "https://www.npmjs.com/package/remark-gfm",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "dependency",
        "requested": "^4.0.1",
        "version": "4.0.1"
      }
    ]
  },
  {
    "name": "stripe",
    "description": "Stripe API wrapper",
    "license": "MIT",
    "url": "https://github.com/stripe/stripe-node",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "dependency",
        "requested": "^20.3.1",
        "version": "20.3.1"
      }
    ]
  },
  {
    "name": "tailwindcss",
    "description": "A utility-first CSS framework for rapidly building custom user interfaces.",
    "license": "MIT",
    "url": "https://tailwindcss.com",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "devDependency",
        "requested": "^4.1.18",
        "version": "4.1.18"
      }
    ]
  },
  {
    "name": "three",
    "description": "JavaScript 3D library",
    "license": "MIT",
    "url": "https://threejs.org/",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "dependency",
        "requested": "^0.182.0",
        "version": "0.182.0"
      }
    ]
  },
  {
    "name": "tsx",
    "description": "TypeScript Execute (tsx): Node.js enhanced with esbuild to run TypeScript & ESM files",
    "license": "MIT",
    "url": "https://tsx.is",
    "occurrences": [
      {
        "workspaceId": "data-core",
        "workspaceLabel": "Data Core",
        "kind": "devDependency",
        "requested": "^4.20.6",
        "version": "4.21.0"
      },
      {
        "workspaceId": "provider-proxy",
        "workspaceLabel": "Provider Proxy",
        "kind": "devDependency",
        "requested": "^4.20.6",
        "version": "4.21.0"
      },
      {
        "workspaceId": "wallet-enclave",
        "workspaceLabel": "Wallet Enclave",
        "kind": "devDependency",
        "requested": "^4.20.6",
        "version": "4.21.0"
      },
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "devDependency",
        "requested": "^4.20.6",
        "version": "4.21.0"
      }
    ]
  },
  {
    "name": "typescript",
    "description": "TypeScript is a language for application scale JavaScript development",
    "license": "Apache-2.0",
    "url": "https://www.typescriptlang.org/",
    "occurrences": [
      {
        "workspaceId": "data-core",
        "workspaceLabel": "Data Core",
        "kind": "devDependency",
        "requested": "^5.8.2",
        "version": "5.9.3"
      },
      {
        "workspaceId": "desktop",
        "workspaceLabel": "Desktop App",
        "kind": "devDependency",
        "requested": "^5.7.3",
        "version": "5.9.3"
      },
      {
        "workspaceId": "provider-proxy",
        "workspaceLabel": "Provider Proxy",
        "kind": "devDependency",
        "requested": "^5.8.2",
        "version": "5.9.3"
      },
      {
        "workspaceId": "wallet-enclave",
        "workspaceLabel": "Wallet Enclave",
        "kind": "devDependency",
        "requested": "^5.8.2",
        "version": "5.9.3"
      },
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "devDependency",
        "requested": "^5.7.3",
        "version": "5.9.3"
      }
    ]
  },
  {
    "name": "ws",
    "description": "Simple to use, blazing fast and thoroughly tested websocket client and server for Node.js",
    "license": "MIT",
    "url": "https://github.com/websockets/ws",
    "occurrences": [
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "dependency",
        "requested": "^8.18.3",
        "version": "8.19.0"
      }
    ]
  },
  {
    "name": "zod",
    "description": "TypeScript-first schema declaration and validation library with static type inference",
    "license": "MIT",
    "url": "https://zod.dev",
    "occurrences": [
      {
        "workspaceId": "data-core",
        "workspaceLabel": "Data Core",
        "kind": "dependency",
        "requested": "^3.25.76",
        "version": "3.25.76"
      },
      {
        "workspaceId": "provider-proxy",
        "workspaceLabel": "Provider Proxy",
        "kind": "dependency",
        "requested": "^3.25.76",
        "version": "3.25.76"
      },
      {
        "workspaceId": "wallet-enclave",
        "workspaceLabel": "Wallet Enclave",
        "kind": "dependency",
        "requested": "^3.25.76",
        "version": "3.25.76"
      },
      {
        "workspaceId": "node",
        "workspaceLabel": "Web App",
        "kind": "dependency",
        "requested": "^4.3.6",
        "version": "4.3.6"
      }
    ]
  }
]
